grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcService.java

Motivation:
- there are unused and .* imports in GRpcServerRunner and
GRpcService
Change:
- Organized imports (using Eclipse defaults)
Result:
- improved imports

Clean up imports

---

build.gradle
grpc-spring-boot-starter/build.gradle

Motivation:
- gradle 2.13 introduced "compileOnly" for compiletime-only dependencies.
Change:
- remove springframework-propdeps plugin
- use compileOnly for "provided" and "optional" dependencies
Result:
- One less gradle plugin needed / more standard features in use

Use "compileOnly" configuration from gradle 2.13

---

build.gradle
grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/DemoApp.java
grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/GreeterService.java
grpc-spring-boot-starter-demo/src/main/resources/application.properties
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DemoAppTestAop.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java

This pull request fixes a bug in the way `GRpcServerRunner` was identifying beans with the `@GRpcService` annotation.  This case was not exposed by the demo, so I updated the demo to expose it.  I updated to the latest version of Spring Boot while I was at it, which exposed a problem accessing the Spring Activator endpoint so I added some configuration to turn off security and make the endpoint accessible again.

Fix @GRpcService annotation detection

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/GRpcAutoConfiguration.java

I would like to suggest to set the `grpcInternalConfigurator` bean name in the GRpcAutoConfiguration using the `name` attribute.
While using `grpc-spring-boot-starter` in a Spring Boot 1.2.x application I realized you can't define a bean only by using `@Bean("grpcInternalConfigurator")`, it introduces an error while creating the bean and generates some injection issues. See full exception below.
Instead of, if you set the name, even the Spring Boot 1.2.x is able to understand and create correctly the bean.
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grpcServerRunner' defined in class path resource [org/lognet/springboot/grpc/autoconfigure/GRpcAutoConfiguration.class]: Unsatisfied dependency expressed through constructor argument …
```

Set bean name using name attribute to avoid Spring Boot injection issue

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/GRpcServerProperties.java

I offer small contribution: set **runningPort** as a volatile variable, cause in `getRunningPort()` we have Double-checked locking. That means we have to set **runningPort** as a volatile variable to prevent extra monitor capture.

volatile for running port

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java

Hi, I offer a small pull request: set name for server awaiting thread.
My motivation is simple: I'm usually curious about the behavior of threads in my application, and I want to know what each thread does.
In the current version, I was a little bit confused to find awaiting thread:
But with this small change, it should be obvious:
PS: also I've removed unnecessary blank lines, but it is not a big deal.

set name for awaiter thread

---

README.adoc
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DemoAppTest.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DemoAppTestAop.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DisabledGrpcServerTest.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/GRpcServerBuilderConfigurerTest.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/OrderedInterceptorsTest.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/RandomGrpcPortTest.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/GRpcServerProperties.java
grpc-spring-boot2-starter-demo/src/test/java/org/lognet/springboot/grpc/ConfigServerEnvironmentBaseTest.java
grpc-spring-boot2-starter-demo/src/test/java/org/lognet/springboot/grpc/ConfigServerEnvironmentTest1.java
grpc-spring-boot2-starter-demo/src/test/java/org/lognet/springboot/grpc/ConfigServerEnvironmentTest2.java
grpc-spring-boot2-starter-demo/src/test/java/org/lognet/springboot/grpc/ConsulRegistrationTest.java

Since `Server.shutdown()` does not wait for preexisting calls to finish, clients will receive an error when the server is shutdown in the middle of an RPC call. See https://github.com/grpc/grpc-java/issues/6511 and https://github.com/grpc/grpc-java/issues/6511.
This PR adds a call to `Server.awaitTermination()` during destroy, with a configurable `shutdownGrace` of how many seconds to wait for preexisting calls to finish before failing the calls and sending a GOAWAY to the clients.
I wasn't quite sure how to test it in the existing setup, so would love suggestions in this area. Thanks!

Proper graceful shutdown with configurable grace period

---

grpc-spring-boot-starter/build.gradle

The dependency configuration `annotationProcessor` was added in Gradle 4.6, and afaik in Gradle 5.x support for running annotation processors from the compileOnly configuration was removed.

Fix configuration annotation processor

---

grpc-client-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/AuthHeader.java

The previous implementation does not care about how many bytes are written to the actual ByteBuffer. It simply uses the backing array which can result in garbage data being used.
Example:
```java
ByteBuffer buf = ByteBuffer.allocate(10).putInt(1337); // only 4 bytes are used
buf.array(); // returns backing byte array with all 10 allocated bytes
buf.remaining(); // returns int 4 because only 4 bytes have been written and therefore only 4 bytes can be read
headerBuf.put(buf); // takes into account buf.remaining()
```

Improve ByteBuffer handling in AuthHeader

---

README.adoc
grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/GreeterService.java
grpc-spring-boot-starter-demo/src/main/proto/greeter.proto
grpc-spring-boot-starter-demo/src/main/protoGen/io/grpc/examples/CalculatorGrpc.java
grpc-spring-boot-starter-demo/src/main/protoGen/io/grpc/examples/GreeterGrpc.java
grpc-spring-boot-starter-demo/src/main/protoGen/io/grpc/examples/GreeterOuterClass.java
grpc-spring-boot-starter-demo/src/main/protoGen/io/grpc/examples/SecuredGreeterGrpc.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/auth/DefaultAuthConfigTest.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/GrpcServiceAuthorizationConfigurer.java

This change allows to add @Secured to any Service/Method without a value specified. Then it only checks if the request is authenticated and sets the authentication accordingly.

Add authentication only check for @Secured

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/GrpcSecurityConfiguration.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/GrpcSecurityConfigurerAdapter.java

`GrpcSecurityConfigurerAdapter` should not fail if oauth2 dependencies are not on classpath.
`BasicAuthSchemeSelector` and `BearerTokenAuthSchemeSelector` are now Spring beans,
`GrpcSecurityConfigurerAdapter` registers them to `authenticationSchemeService` automatically
if they are in context.
`BearerTokenAuthSchemeSelector` has condition for instantiation:
```java
@Bean
@ConditionalOnClass(name = {
"org.springframework.security.oauth2.server.resource.BearerTokenAuthenticationToken",
"org.springframework.security.oauth2.core.OAuth2AuthenticationException"})
public BearerTokenAuthSchemeSelector bearerTokenAuthSchemeSelector() {
return new BearerTokenAuthSchemeSelector();
}
```

176: Fix exception GrpcSecurityConfigurerAdapter initialization

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/security/SecurityAutoConfiguration.java

Applications that do not use `@GRpcService` will fail to start with the following error unless `grpc.security.auth.enabled = false` is set.
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Method springGrpcSecurityInterceptor in org.lognet.springboot.grpc.security.GrpcSecurityConfiguration required a bean of type 'org.lognet.springboot.grpc.autoconfigure.GRpcServerProperties' that could not be found.
Action:
Consider defining a bean of type 'org.lognet.springboot.grpc.autoconfigure.GRpcServerProperties' in your configuration.
```
This behavior is likely due to the `org.lognet.springboot.grpc.autoconfigure.security.Security.SecurityAutoConfiguration` added in release 4.5.0, which creates a dependency on `GRpcServerProperties`. This seems …

After updating to 4.5.0, startup fails unless grpc.security.auth.enabled = false is specified

---

grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/HalfCloseInterceptor.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/ValidationTest.java
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/auth/FailLateSecurityInterceptorTest.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/FailureHandlingServerInterceptor.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/SecurityInterceptor.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/validation/ValidatingInterceptor.java

Block onHalfClose if onMessage was blocked

---

grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/GreeterService.java
grpc-spring-boot-starter-demo/src/main/proto/greeter.proto
grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/GrpcMeterTest.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/metrics/GRpcMetricsAutoConfiguration.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/metrics/RequestAwareGRpcMetricsTagsContributor.java

closes #244
… and also refactor the metric code a bit.

Support RequestAwareGRpcMetricsTagsContributor on Multiary Calls

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/actuate/GRpcActuateAutoConfiguration.java

Cannot start with the following error if there is no GRpcService.
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of method grpcEndpoint in org.lognet.springboot.grpc.autoconfigure.actuate.GRpcActuateAutoConfiguration$GrpcEndpointConfiguration required a bean of type 'org.lognet.springboot.grpc.GRpcServicesRegistry' that could not be found.
Action:
Consider defining a bean of type 'org.lognet.springboot.grpc.GRpcServicesRegistry' in your configuration.
```
The preceding GRpcAutoConfiguration is suppressed by the presence of GRpcService, but, GRpcActuateAutoConfiguration is enabled regardless of whether GRpcService is present or not.
I have had #209 merged before with a similar problem.
This PR is similar, with
* Suppress …

Cannot boot if there is no GRpcService

---

README.adoc

The first param of `ClientInterceptors.intercept` should be a `io.grpc.Channel`, but not a builder

doc: fix client interceptors intercept demo

---

README.adoc

Key for authorization is specified incorrectly in wiki. There should be "Authorization" instead of "Authentication".
The value in [Constants](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/Constants.java) is correct, but not used in [SecurityInterceptor](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/SecurityInterceptor.java)(137-139 lines).

Fixed wiki

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/GrpcServiceAuthorizationConfigurer.java

As discussed in https://github.com/LogNet/grpc-spring-boot-starter/discussions/286, it's really helpful to secure all services  or methods APART FROM a few. Basically applying security by default. 
This PR adds 2 convenience methods achieving this.
Missing from this PR are tests verifying the new methods. Unfortunately, I'm not the biggest expect in everything Java, Spring boot and gradle, so I'm having some difficulties understanding how tests are setup here and what the best way to test this are. If we want tests were, I'd appreciate some guidance. 
As far as I understand, the least intrusive way might be to to something similar to `JwtRoleTest` and call two different methods - one secured and one unsecured and see if I get an error if I don't provide a JWT token.

Added methods for excluding secured methods and services from GrpcSecurity

---

grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/recovery/GRpcStatusRuntimeExceptionTest.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/FailureHandlingSupport.java
grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerMethodResolver.java

Copy status from StatusRuntimeException if no handler method is present in FailureHandlingSupport.

Copy status from StatusRuntimeException in FailureHandlingSupport

---

grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/GRpcAutoConfiguration.java

The current version does not start the in-process server when setting the property by the name "in-process-server-name," even though it is in accordance with the generated **spring-configuration-metadata.json**.
The issue lies in ConditionalOnProperty, as it does not support relaxed names, as reported in https://github.com/spring-projects/spring-boot/issues/12282.
The proposed change aims to address this limitation. With the proposed change, all relaxed versions of the property name would work, including "in-process-server-name," "inProcessServerName," "in_process_server_name," and "IN_PROCESS_SERVER_NAME."

Fixes autoconfiguration to accept standard version of "inProcessServeName" property

---

README.adoc

Description:
This PR updates the README.adoc file to replace the `compile` keyword with `implementation` in the Gradle dependencies section, as `compile` is no longer supported in Gradle 7.0 and above.
Changes:
Replaced `compile` with `implementation` in the Gradle dependencies section of README.adoc.
Reason:
The `compile` keyword became unsupported in Gradle 7.0, leading to build failures. Replacing it with `implementation` ensures compatibility and successful builds for users on Gradle 7.0 and newer.

Update README.adoc to Replace `compile` with `implementation`
